[package]
name = "gpu-temp-watch"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trayicon = "0.1"
winrt-notification = "0.5"

[profile.release]
opt-level = "s"
lto = true
panic = "abort"
strip = true
